### ISSUE TITLE
explore the idea of quarterly projects

### ISSUE THREAD

**Issue by morgane** [morgane/pixel-lab#2]
maybe have a theme each quarter ("light", "spheres", etc) and have people work on something related to that. wrap each project up at the end of the quarter and move on

**Comment by nickbytes** [comment]
Adding this in case gets lost in slack. 

> Some of these New Inquiry issue themes would make good quarterly themes for projects.
![screen shot 2017-06-20 at 9 47 35 am](https://user-images.githubusercontent.com/3009331/27336756-82bff824-559e-11e7-86be-a13b33f82ca9.png)
